### ISSUE TITLE
Just add useUnifiedToplogy:true in the connection string, it gives a warning, I have to change it manually everytime

### ISSUE THREAD

**Issue by dheereshaggarwal** [roerohan/vscode-MongoSnippets-NodeJS#20]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by dheereshaggarwal** [comment]
In mongoose.connect

**Comment by roerohan** [comment]
https://github.com/roerohan/vscode-MongoSnippets-NodeJS/blob/master/src/boilerplate/precode.json#L22

I thought it was there already
