### ISSUE TITLE
Can we debugger the js after write on VSCode?

### ISSUE THREAD

**Issue by robyle** [roerohan/vscode-MongoSnippets-NodeJS#21]
if I want simplely use the mongodb query on debugger my written js file.

**Comment by roerohan** [comment]
Hey, I didn't exactly get what you mean by that.

**Comment by robyle** [comment]
> Hey, I didn't exactly get what you mean by that.

My means: after me written a mdb.js file. Can I debugger it ? just like in chrome browser's js file, I can break on one line. and watch the var changes.

**Comment by roerohan** [comment]
Sorry, the extension does not support this feature as of now. I have not been maintaining this recently due to other commitments. Any contributions to the extension are welcome!
