### ISSUE TITLE
Async Await

### ISSUE THREAD

**Issue by roerohan** [roerohan/vscode-MongoSnippets-NodeJS#9]
**Is your feature request related to a problem? Please describe.**
Callback hell in code.

**Describe the solution you'd like**
Use async-await in JavaScript to make the code structure linear.

**Describe alternatives you've considered**
You may use asynchronous fs functions if it works without any issues.

**Additional context**
N.A.

> Please test and review the code before filing a PR.

[See File](https://github.com/roerohan/vscode-MongoSnippets-NodeJS/blob/4c388ab7abd37daf3610417622b7e2c515edf9ca/src/suggestions/getModelNames.js#L6-L110)

**Comment by VickyKoblinski** [comment]
I'd like to help!
